package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbAttendance generated by hbm2java
 */
@Entity
@Table(name="tb_attendance"
    ,catalog="saminko_attendance_system"
)
public class TbAttendance  implements java.io.Serializable {


     private Integer idattendance;
     private TbClass tbClass;
     private TbStudent tbStudent;
     private String attendanceDate;
     private String attendanceTime;
     private String attendanceStatus;

    public TbAttendance() {
    }

	
    public TbAttendance(TbClass tbClass, TbStudent tbStudent) {
        this.tbClass = tbClass;
        this.tbStudent = tbStudent;
    }
    public TbAttendance(TbClass tbClass, TbStudent tbStudent, String attendanceDate, String attendanceTime, String attendanceStatus) {
       this.tbClass = tbClass;
       this.tbStudent = tbStudent;
       this.attendanceDate = attendanceDate;
       this.attendanceTime = attendanceTime;
       this.attendanceStatus = attendanceStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idattendance", unique=true, nullable=false)
    public Integer getIdattendance() {
        return this.idattendance;
    }
    
    public void setIdattendance(Integer idattendance) {
        this.idattendance = idattendance;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_idclass", nullable=false)
    public TbClass getTbClass() {
        return this.tbClass;
    }
    
    public void setTbClass(TbClass tbClass) {
        this.tbClass = tbClass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_idstudent", nullable=false)
    public TbStudent getTbStudent() {
        return this.tbStudent;
    }
    
    public void setTbStudent(TbStudent tbStudent) {
        this.tbStudent = tbStudent;
    }

    
    @Column(name="attendance_date", length=45)
    public String getAttendanceDate() {
        return this.attendanceDate;
    }
    
    public void setAttendanceDate(String attendanceDate) {
        this.attendanceDate = attendanceDate;
    }

    
    @Column(name="attendance_time", length=45)
    public String getAttendanceTime() {
        return this.attendanceTime;
    }
    
    public void setAttendanceTime(String attendanceTime) {
        this.attendanceTime = attendanceTime;
    }

    
    @Column(name="attendance_status", length=45)
    public String getAttendanceStatus() {
        return this.attendanceStatus;
    }
    
    public void setAttendanceStatus(String attendanceStatus) {
        this.attendanceStatus = attendanceStatus;
    }




}


