package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCategory generated by hbm2java
 */
@Entity
@Table(name="tb_category"
    ,catalog="saminko_attendance_system"
)
public class TbCategory  implements java.io.Serializable {


     private Integer idcategory;
     private String categoryName;
     private String categoryStatus;
     private Set<TbClass> tbClasses = new HashSet<TbClass>(0);

    public TbCategory() {
    }

    public TbCategory(String categoryName, String categoryStatus, Set<TbClass> tbClasses) {
       this.categoryName = categoryName;
       this.categoryStatus = categoryStatus;
       this.tbClasses = tbClasses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcategory", unique=true, nullable=false)
    public Integer getIdcategory() {
        return this.idcategory;
    }
    
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }

    
    @Column(name="category_name", length=45)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    @Column(name="category_status", length=45)
    public String getCategoryStatus() {
        return this.categoryStatus;
    }
    
    public void setCategoryStatus(String categoryStatus) {
        this.categoryStatus = categoryStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCategory")
    public Set<TbClass> getTbClasses() {
        return this.tbClasses;
    }
    
    public void setTbClasses(Set<TbClass> tbClasses) {
        this.tbClasses = tbClasses;
    }




}


