package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbClassHasTute generated by hbm2java
 */
@Entity
@Table(name="tb_class_has_tute"
    ,catalog="saminko_attendance_system"
)
public class TbClassHasTute  implements java.io.Serializable {


     private Integer idclassHasTute;
     private TbClass tbClass;
     private TbTute tbTute;
     private String classHasTuteStatus;

    public TbClassHasTute() {
    }

	
    public TbClassHasTute(TbClass tbClass, TbTute tbTute) {
        this.tbClass = tbClass;
        this.tbTute = tbTute;
    }
    public TbClassHasTute(TbClass tbClass, TbTute tbTute, String classHasTuteStatus) {
       this.tbClass = tbClass;
       this.tbTute = tbTute;
       this.classHasTuteStatus = classHasTuteStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idclass_has_tute", unique=true, nullable=false)
    public Integer getIdclassHasTute() {
        return this.idclassHasTute;
    }
    
    public void setIdclassHasTute(Integer idclassHasTute) {
        this.idclassHasTute = idclassHasTute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_idclass", nullable=false)
    public TbClass getTbClass() {
        return this.tbClass;
    }
    
    public void setTbClass(TbClass tbClass) {
        this.tbClass = tbClass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tute_idtute", nullable=false)
    public TbTute getTbTute() {
        return this.tbTute;
    }
    
    public void setTbTute(TbTute tbTute) {
        this.tbTute = tbTute;
    }

    
    @Column(name="class_has_tute_status", length=45)
    public String getClassHasTuteStatus() {
        return this.classHasTuteStatus;
    }
    
    public void setClassHasTuteStatus(String classHasTuteStatus) {
        this.classHasTuteStatus = classHasTuteStatus;
    }




}


