package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbPages generated by hbm2java
 */
@Entity
@Table(name="tb_pages"
    ,catalog="saminko_attendance_system"
)
public class TbPages  implements java.io.Serializable {


     private Integer idpages;
     private int pagesId;
     private String page;
     private String pagesStatus;
     private Set<TbPrivilageHasPages> tbPrivilageHasPageses = new HashSet<TbPrivilageHasPages>(0);

    public TbPages() {
    }

	
    public TbPages(int pagesId) {
        this.pagesId = pagesId;
    }
    public TbPages(int pagesId, String page, String pagesStatus, Set<TbPrivilageHasPages> tbPrivilageHasPageses) {
       this.pagesId = pagesId;
       this.page = page;
       this.pagesStatus = pagesStatus;
       this.tbPrivilageHasPageses = tbPrivilageHasPageses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpages", unique=true, nullable=false)
    public Integer getIdpages() {
        return this.idpages;
    }
    
    public void setIdpages(Integer idpages) {
        this.idpages = idpages;
    }

    
    @Column(name="pages_id", nullable=false)
    public int getPagesId() {
        return this.pagesId;
    }
    
    public void setPagesId(int pagesId) {
        this.pagesId = pagesId;
    }

    
    @Column(name="page", length=45)
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }

    
    @Column(name="pages_status", length=45)
    public String getPagesStatus() {
        return this.pagesStatus;
    }
    
    public void setPagesStatus(String pagesStatus) {
        this.pagesStatus = pagesStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbPages")
    public Set<TbPrivilageHasPages> getTbPrivilageHasPageses() {
        return this.tbPrivilageHasPageses;
    }
    
    public void setTbPrivilageHasPageses(Set<TbPrivilageHasPages> tbPrivilageHasPageses) {
        this.tbPrivilageHasPageses = tbPrivilageHasPageses;
    }




}


