package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbPrivilage generated by hbm2java
 */
@Entity
@Table(name="tb_privilage"
    ,catalog="saminko_attendance_system"
)
public class TbPrivilage  implements java.io.Serializable {


     private Integer idprivilage;
     private TbUserType tbUserType;
     private int privilageId;
     private String privilageName;
     private String privilageStatus;
     private int userTypeUserTypeId;
     private Set<TbPrivilageHasPages> tbPrivilageHasPageses = new HashSet<TbPrivilageHasPages>(0);

    public TbPrivilage() {
    }

	
    public TbPrivilage(TbUserType tbUserType, int privilageId, int userTypeUserTypeId) {
        this.tbUserType = tbUserType;
        this.privilageId = privilageId;
        this.userTypeUserTypeId = userTypeUserTypeId;
    }
    public TbPrivilage(TbUserType tbUserType, int privilageId, String privilageName, String privilageStatus, int userTypeUserTypeId, Set<TbPrivilageHasPages> tbPrivilageHasPageses) {
       this.tbUserType = tbUserType;
       this.privilageId = privilageId;
       this.privilageName = privilageName;
       this.privilageStatus = privilageStatus;
       this.userTypeUserTypeId = userTypeUserTypeId;
       this.tbPrivilageHasPageses = tbPrivilageHasPageses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprivilage", unique=true, nullable=false)
    public Integer getIdprivilage() {
        return this.idprivilage;
    }
    
    public void setIdprivilage(Integer idprivilage) {
        this.idprivilage = idprivilage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_type_iduser_type", nullable=false)
    public TbUserType getTbUserType() {
        return this.tbUserType;
    }
    
    public void setTbUserType(TbUserType tbUserType) {
        this.tbUserType = tbUserType;
    }

    
    @Column(name="privilage_id", nullable=false)
    public int getPrivilageId() {
        return this.privilageId;
    }
    
    public void setPrivilageId(int privilageId) {
        this.privilageId = privilageId;
    }

    
    @Column(name="privilage_name", length=45)
    public String getPrivilageName() {
        return this.privilageName;
    }
    
    public void setPrivilageName(String privilageName) {
        this.privilageName = privilageName;
    }

    
    @Column(name="privilage_status", length=45)
    public String getPrivilageStatus() {
        return this.privilageStatus;
    }
    
    public void setPrivilageStatus(String privilageStatus) {
        this.privilageStatus = privilageStatus;
    }

    
    @Column(name="user_type_user_type_id", nullable=false)
    public int getUserTypeUserTypeId() {
        return this.userTypeUserTypeId;
    }
    
    public void setUserTypeUserTypeId(int userTypeUserTypeId) {
        this.userTypeUserTypeId = userTypeUserTypeId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbPrivilage")
    public Set<TbPrivilageHasPages> getTbPrivilageHasPageses() {
        return this.tbPrivilageHasPageses;
    }
    
    public void setTbPrivilageHasPageses(Set<TbPrivilageHasPages> tbPrivilageHasPageses) {
        this.tbPrivilageHasPageses = tbPrivilageHasPageses;
    }




}


