package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbPrivilageHasPages generated by hbm2java
 */
@Entity
@Table(name="tb_privilage_has_pages"
    ,catalog="saminko_attendance_system"
)
public class TbPrivilageHasPages  implements java.io.Serializable {


     private Integer idprivilageHasPages;
     private TbPages tbPages;
     private TbPrivilage tbPrivilage;
     private String privilageHasPagesStatus;

    public TbPrivilageHasPages() {
    }

	
    public TbPrivilageHasPages(TbPages tbPages, TbPrivilage tbPrivilage) {
        this.tbPages = tbPages;
        this.tbPrivilage = tbPrivilage;
    }
    public TbPrivilageHasPages(TbPages tbPages, TbPrivilage tbPrivilage, String privilageHasPagesStatus) {
       this.tbPages = tbPages;
       this.tbPrivilage = tbPrivilage;
       this.privilageHasPagesStatus = privilageHasPagesStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprivilage_has_pages", unique=true, nullable=false)
    public Integer getIdprivilageHasPages() {
        return this.idprivilageHasPages;
    }
    
    public void setIdprivilageHasPages(Integer idprivilageHasPages) {
        this.idprivilageHasPages = idprivilageHasPages;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pages_idpages", nullable=false)
    public TbPages getTbPages() {
        return this.tbPages;
    }
    
    public void setTbPages(TbPages tbPages) {
        this.tbPages = tbPages;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="privilage_idprivilage", nullable=false)
    public TbPrivilage getTbPrivilage() {
        return this.tbPrivilage;
    }
    
    public void setTbPrivilage(TbPrivilage tbPrivilage) {
        this.tbPrivilage = tbPrivilage;
    }

    
    @Column(name="privilage_has_pages_status", length=45)
    public String getPrivilageHasPagesStatus() {
        return this.privilageHasPagesStatus;
    }
    
    public void setPrivilageHasPagesStatus(String privilageHasPagesStatus) {
        this.privilageHasPagesStatus = privilageHasPagesStatus;
    }




}


