package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbStudentHasClass generated by hbm2java
 */
@Entity
@Table(name="tb_student_has_class"
    ,catalog="saminko_attendance_system"
)
public class TbStudentHasClass  implements java.io.Serializable {


     private Integer idstudentHasClass;
     private TbClass tbClass;
     private TbStudent tbStudent;
     private String studentHasClassStatus;

    public TbStudentHasClass() {
    }

	
    public TbStudentHasClass(TbClass tbClass, TbStudent tbStudent) {
        this.tbClass = tbClass;
        this.tbStudent = tbStudent;
    }
    public TbStudentHasClass(TbClass tbClass, TbStudent tbStudent, String studentHasClassStatus) {
       this.tbClass = tbClass;
       this.tbStudent = tbStudent;
       this.studentHasClassStatus = studentHasClassStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstudent_has_class", unique=true, nullable=false)
    public Integer getIdstudentHasClass() {
        return this.idstudentHasClass;
    }
    
    public void setIdstudentHasClass(Integer idstudentHasClass) {
        this.idstudentHasClass = idstudentHasClass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_idclass", nullable=false)
    public TbClass getTbClass() {
        return this.tbClass;
    }
    
    public void setTbClass(TbClass tbClass) {
        this.tbClass = tbClass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_idstudent", nullable=false)
    public TbStudent getTbStudent() {
        return this.tbStudent;
    }
    
    public void setTbStudent(TbStudent tbStudent) {
        this.tbStudent = tbStudent;
    }

    
    @Column(name="student_has_class_status", length=45)
    public String getStudentHasClassStatus() {
        return this.studentHasClassStatus;
    }
    
    public void setStudentHasClassStatus(String studentHasClassStatus) {
        this.studentHasClassStatus = studentHasClassStatus;
    }




}


