package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbStudentHasExam generated by hbm2java
 */
@Entity
@Table(name="tb_student_has_exam"
    ,catalog="saminko_attendance_system"
)
public class TbStudentHasExam  implements java.io.Serializable {


     private Integer idstudentHasExam;
     private TbExam tbExam;
     private TbStudent tbStudent;
     private String examMarks;
     private String examCredit;
     private String studentHasExamStatus;

    public TbStudentHasExam() {
    }

	
    public TbStudentHasExam(TbExam tbExam, TbStudent tbStudent) {
        this.tbExam = tbExam;
        this.tbStudent = tbStudent;
    }
    public TbStudentHasExam(TbExam tbExam, TbStudent tbStudent, String examMarks, String examCredit, String studentHasExamStatus) {
       this.tbExam = tbExam;
       this.tbStudent = tbStudent;
       this.examMarks = examMarks;
       this.examCredit = examCredit;
       this.studentHasExamStatus = studentHasExamStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstudent_has_exam", unique=true, nullable=false)
    public Integer getIdstudentHasExam() {
        return this.idstudentHasExam;
    }
    
    public void setIdstudentHasExam(Integer idstudentHasExam) {
        this.idstudentHasExam = idstudentHasExam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exam_idexam", nullable=false)
    public TbExam getTbExam() {
        return this.tbExam;
    }
    
    public void setTbExam(TbExam tbExam) {
        this.tbExam = tbExam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_idstudent", nullable=false)
    public TbStudent getTbStudent() {
        return this.tbStudent;
    }
    
    public void setTbStudent(TbStudent tbStudent) {
        this.tbStudent = tbStudent;
    }

    
    @Column(name="exam_marks", length=45)
    public String getExamMarks() {
        return this.examMarks;
    }
    
    public void setExamMarks(String examMarks) {
        this.examMarks = examMarks;
    }

    
    @Column(name="exam_credit", length=45)
    public String getExamCredit() {
        return this.examCredit;
    }
    
    public void setExamCredit(String examCredit) {
        this.examCredit = examCredit;
    }

    
    @Column(name="student_has_exam_status", length=45)
    public String getStudentHasExamStatus() {
        return this.studentHasExamStatus;
    }
    
    public void setStudentHasExamStatus(String studentHasExamStatus) {
        this.studentHasExamStatus = studentHasExamStatus;
    }




}


