package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbStudentHasPayment generated by hbm2java
 */
@Entity
@Table(name="tb_student_has_payment"
    ,catalog="saminko_attendance_system"
)
public class TbStudentHasPayment  implements java.io.Serializable {


     private Integer idstudentHasPayment;
     private TbPayment tbPayment;
     private TbStudent tbStudent;
     private String studentHasPaymentStatus;

    public TbStudentHasPayment() {
    }

	
    public TbStudentHasPayment(TbPayment tbPayment, TbStudent tbStudent) {
        this.tbPayment = tbPayment;
        this.tbStudent = tbStudent;
    }
    public TbStudentHasPayment(TbPayment tbPayment, TbStudent tbStudent, String studentHasPaymentStatus) {
       this.tbPayment = tbPayment;
       this.tbStudent = tbStudent;
       this.studentHasPaymentStatus = studentHasPaymentStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstudent_has_payment", unique=true, nullable=false)
    public Integer getIdstudentHasPayment() {
        return this.idstudentHasPayment;
    }
    
    public void setIdstudentHasPayment(Integer idstudentHasPayment) {
        this.idstudentHasPayment = idstudentHasPayment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_idpayment", nullable=false)
    public TbPayment getTbPayment() {
        return this.tbPayment;
    }
    
    public void setTbPayment(TbPayment tbPayment) {
        this.tbPayment = tbPayment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_idstudent", nullable=false)
    public TbStudent getTbStudent() {
        return this.tbStudent;
    }
    
    public void setTbStudent(TbStudent tbStudent) {
        this.tbStudent = tbStudent;
    }

    
    @Column(name="student_has_payment_status", length=45)
    public String getStudentHasPaymentStatus() {
        return this.studentHasPaymentStatus;
    }
    
    public void setStudentHasPaymentStatus(String studentHasPaymentStatus) {
        this.studentHasPaymentStatus = studentHasPaymentStatus;
    }




}


