package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbStudent generated by hbm2java
 */
@Entity
@Table(name="tb_student"
    ,catalog="saminko_attendance_system"
)
public class TbStudent  implements java.io.Serializable {


     private Integer idstudent;
     private String studentId;
     private String studentName;
     private String studentEmail;
     private String studentPhone;
     private String studentParentNo;
     private String studentParentName;
     private String studentStatus;
     private Set<TbAttendance> tbAttendances = new HashSet<TbAttendance>(0);
     private Set<TbStudentHasExam> tbStudentHasExams = new HashSet<TbStudentHasExam>(0);
     private Set<TbStudentHasPayment> tbStudentHasPayments = new HashSet<TbStudentHasPayment>(0);
     private Set<TbStudentHasClass> tbStudentHasClasses = new HashSet<TbStudentHasClass>(0);

    public TbStudent() {
    }

	
    public TbStudent(String studentId) {
        this.studentId = studentId;
    }
    public TbStudent(String studentId, String studentName, String studentEmail, String studentPhone, String studentParentNo, String studentParentName, String studentStatus, Set<TbAttendance> tbAttendances, Set<TbStudentHasExam> tbStudentHasExams, Set<TbStudentHasPayment> tbStudentHasPayments, Set<TbStudentHasClass> tbStudentHasClasses) {
       this.studentId = studentId;
       this.studentName = studentName;
       this.studentEmail = studentEmail;
       this.studentPhone = studentPhone;
       this.studentParentNo = studentParentNo;
       this.studentParentName = studentParentName;
       this.studentStatus = studentStatus;
       this.tbAttendances = tbAttendances;
       this.tbStudentHasExams = tbStudentHasExams;
       this.tbStudentHasPayments = tbStudentHasPayments;
       this.tbStudentHasClasses = tbStudentHasClasses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstudent", unique=true, nullable=false)
    public Integer getIdstudent() {
        return this.idstudent;
    }
    
    public void setIdstudent(Integer idstudent) {
        this.idstudent = idstudent;
    }

    
    @Column(name="student_id", nullable=false, length=45)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="student_name", length=45)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    
    @Column(name="student_email", length=45)
    public String getStudentEmail() {
        return this.studentEmail;
    }
    
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail;
    }

    
    @Column(name="student_phone", length=45)
    public String getStudentPhone() {
        return this.studentPhone;
    }
    
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone;
    }

    
    @Column(name="student_parent_no", length=45)
    public String getStudentParentNo() {
        return this.studentParentNo;
    }
    
    public void setStudentParentNo(String studentParentNo) {
        this.studentParentNo = studentParentNo;
    }

    
    @Column(name="student_parent_name", length=45)
    public String getStudentParentName() {
        return this.studentParentName;
    }
    
    public void setStudentParentName(String studentParentName) {
        this.studentParentName = studentParentName;
    }

    
    @Column(name="student_status", length=45)
    public String getStudentStatus() {
        return this.studentStatus;
    }
    
    public void setStudentStatus(String studentStatus) {
        this.studentStatus = studentStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbStudent")
    public Set<TbAttendance> getTbAttendances() {
        return this.tbAttendances;
    }
    
    public void setTbAttendances(Set<TbAttendance> tbAttendances) {
        this.tbAttendances = tbAttendances;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbStudent")
    public Set<TbStudentHasExam> getTbStudentHasExams() {
        return this.tbStudentHasExams;
    }
    
    public void setTbStudentHasExams(Set<TbStudentHasExam> tbStudentHasExams) {
        this.tbStudentHasExams = tbStudentHasExams;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbStudent")
    public Set<TbStudentHasPayment> getTbStudentHasPayments() {
        return this.tbStudentHasPayments;
    }
    
    public void setTbStudentHasPayments(Set<TbStudentHasPayment> tbStudentHasPayments) {
        this.tbStudentHasPayments = tbStudentHasPayments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbStudent")
    public Set<TbStudentHasClass> getTbStudentHasClasses() {
        return this.tbStudentHasClasses;
    }
    
    public void setTbStudentHasClasses(Set<TbStudentHasClass> tbStudentHasClasses) {
        this.tbStudentHasClasses = tbStudentHasClasses;
    }




}


