package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbTute generated by hbm2java
 */
@Entity
@Table(name="tb_tute"
    ,catalog="saminko_attendance_system"
)
public class TbTute  implements java.io.Serializable {


     private Integer idtute;
     private int tuteId;
     private String tuteNo;
     private String tuteName;
     private String tuteStatus;
     private Set<TbClassHasTute> tbClassHasTutes = new HashSet<TbClassHasTute>(0);

    public TbTute() {
    }

	
    public TbTute(int tuteId) {
        this.tuteId = tuteId;
    }
    public TbTute(int tuteId, String tuteNo, String tuteName, String tuteStatus, Set<TbClassHasTute> tbClassHasTutes) {
       this.tuteId = tuteId;
       this.tuteNo = tuteNo;
       this.tuteName = tuteName;
       this.tuteStatus = tuteStatus;
       this.tbClassHasTutes = tbClassHasTutes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtute", unique=true, nullable=false)
    public Integer getIdtute() {
        return this.idtute;
    }
    
    public void setIdtute(Integer idtute) {
        this.idtute = idtute;
    }

    
    @Column(name="tute_id", nullable=false)
    public int getTuteId() {
        return this.tuteId;
    }
    
    public void setTuteId(int tuteId) {
        this.tuteId = tuteId;
    }

    
    @Column(name="tute_no", length=45)
    public String getTuteNo() {
        return this.tuteNo;
    }
    
    public void setTuteNo(String tuteNo) {
        this.tuteNo = tuteNo;
    }

    
    @Column(name="tute_name", length=45)
    public String getTuteName() {
        return this.tuteName;
    }
    
    public void setTuteName(String tuteName) {
        this.tuteName = tuteName;
    }

    
    @Column(name="tute_status", length=45)
    public String getTuteStatus() {
        return this.tuteStatus;
    }
    
    public void setTuteStatus(String tuteStatus) {
        this.tuteStatus = tuteStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbTute")
    public Set<TbClassHasTute> getTbClassHasTutes() {
        return this.tbClassHasTutes;
    }
    
    public void setTbClassHasTutes(Set<TbClassHasTute> tbClassHasTutes) {
        this.tbClassHasTutes = tbClassHasTutes;
    }




}


