package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbType generated by hbm2java
 */
@Entity
@Table(name="tb_type"
    ,catalog="saminko_attendance_system"
)
public class TbType  implements java.io.Serializable {


     private Integer idtype;
     private String typeName;
     private String typeStatus;
     private Set<TbClass> tbClasses = new HashSet<TbClass>(0);

    public TbType() {
    }

    public TbType(String typeName, String typeStatus, Set<TbClass> tbClasses) {
       this.typeName = typeName;
       this.typeStatus = typeStatus;
       this.tbClasses = tbClasses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtype", unique=true, nullable=false)
    public Integer getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(Integer idtype) {
        this.idtype = idtype;
    }

    
    @Column(name="type_name", length=45)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    
    @Column(name="type_status", length=45)
    public String getTypeStatus() {
        return this.typeStatus;
    }
    
    public void setTypeStatus(String typeStatus) {
        this.typeStatus = typeStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbType")
    public Set<TbClass> getTbClasses() {
        return this.tbClasses;
    }
    
    public void setTbClasses(Set<TbClass> tbClasses) {
        this.tbClasses = tbClasses;
    }




}


