package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbUserAccount generated by hbm2java
 */
@Entity
@Table(name="tb_user_account"
    ,catalog="saminko_attendance_system"
)
public class TbUserAccount  implements java.io.Serializable {


     private Integer iduserAccount;
     private TbUserType tbUserType;
     private int userAccountId;
     private String userAccountEmail;
     private String userAccountPassword;
     private String userAccountForget;
     private String userAccountStatus;

    public TbUserAccount() {
    }

	
    public TbUserAccount(TbUserType tbUserType, int userAccountId) {
        this.tbUserType = tbUserType;
        this.userAccountId = userAccountId;
    }
    public TbUserAccount(TbUserType tbUserType, int userAccountId, String userAccountEmail, String userAccountPassword, String userAccountForget, String userAccountStatus) {
       this.tbUserType = tbUserType;
       this.userAccountId = userAccountId;
       this.userAccountEmail = userAccountEmail;
       this.userAccountPassword = userAccountPassword;
       this.userAccountForget = userAccountForget;
       this.userAccountStatus = userAccountStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduser_account", unique=true, nullable=false)
    public Integer getIduserAccount() {
        return this.iduserAccount;
    }
    
    public void setIduserAccount(Integer iduserAccount) {
        this.iduserAccount = iduserAccount;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_type_iduser_type", nullable=false)
    public TbUserType getTbUserType() {
        return this.tbUserType;
    }
    
    public void setTbUserType(TbUserType tbUserType) {
        this.tbUserType = tbUserType;
    }

    
    @Column(name="user_account_id", nullable=false)
    public int getUserAccountId() {
        return this.userAccountId;
    }
    
    public void setUserAccountId(int userAccountId) {
        this.userAccountId = userAccountId;
    }

    
    @Column(name="user_account_email", length=45)
    public String getUserAccountEmail() {
        return this.userAccountEmail;
    }
    
    public void setUserAccountEmail(String userAccountEmail) {
        this.userAccountEmail = userAccountEmail;
    }

    
    @Column(name="user_account_password", length=45)
    public String getUserAccountPassword() {
        return this.userAccountPassword;
    }
    
    public void setUserAccountPassword(String userAccountPassword) {
        this.userAccountPassword = userAccountPassword;
    }

    
    @Column(name="user_account_forget", length=45)
    public String getUserAccountForget() {
        return this.userAccountForget;
    }
    
    public void setUserAccountForget(String userAccountForget) {
        this.userAccountForget = userAccountForget;
    }

    
    @Column(name="user_account_status", length=45)
    public String getUserAccountStatus() {
        return this.userAccountStatus;
    }
    
    public void setUserAccountStatus(String userAccountStatus) {
        this.userAccountStatus = userAccountStatus;
    }




}


