package com.fgs.fsc_model;
// Generated Jan 30, 2017 9:37:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbUserType generated by hbm2java
 */
@Entity
@Table(name="tb_user_type"
    ,catalog="saminko_attendance_system"
)
public class TbUserType  implements java.io.Serializable {


     private Integer iduserType;
     private String userType;
     private String userTypeStatus;
     private Set<TbUserAccount> tbUserAccounts = new HashSet<TbUserAccount>(0);
     private Set<TbPrivilage> tbPrivilages = new HashSet<TbPrivilage>(0);

    public TbUserType() {
    }

    public TbUserType(String userType, String userTypeStatus, Set<TbUserAccount> tbUserAccounts, Set<TbPrivilage> tbPrivilages) {
       this.userType = userType;
       this.userTypeStatus = userTypeStatus;
       this.tbUserAccounts = tbUserAccounts;
       this.tbPrivilages = tbPrivilages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduser_type", unique=true, nullable=false)
    public Integer getIduserType() {
        return this.iduserType;
    }
    
    public void setIduserType(Integer iduserType) {
        this.iduserType = iduserType;
    }

    
    @Column(name="user_type", length=45)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }

    
    @Column(name="user_type_status", length=45)
    public String getUserTypeStatus() {
        return this.userTypeStatus;
    }
    
    public void setUserTypeStatus(String userTypeStatus) {
        this.userTypeStatus = userTypeStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbUserType")
    public Set<TbUserAccount> getTbUserAccounts() {
        return this.tbUserAccounts;
    }
    
    public void setTbUserAccounts(Set<TbUserAccount> tbUserAccounts) {
        this.tbUserAccounts = tbUserAccounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbUserType")
    public Set<TbPrivilage> getTbPrivilages() {
        return this.tbPrivilages;
    }
    
    public void setTbPrivilages(Set<TbPrivilage> tbPrivilages) {
        this.tbPrivilages = tbPrivilages;
    }




}


